# Generated by Django 3.1.7 on 2021-03-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210311_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='email',
            new_name='temail',
        ),
    ]
