# Generated by Django 3.1.7 on 2021-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210311_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='gender',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
