# Generated by Django 3.1.7 on 2021-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user_data_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demail', models.CharField(max_length=30)),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
