# Generated by Django 3.1.7 on 2021-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_drive_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive_data',
            name='filename',
            field=models.CharField(default='nothing', max_length=30),
        ),
    ]
