# Generated by Django 3.1.7 on 2021-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_drive_data_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive_data',
            name='ext',
            field=models.CharField(default='nothing', max_length=10),
        ),
    ]
