# Generated by Django 3.1.7 on 2021-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_drive_data_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive_data',
            name='description',
            field=models.CharField(default='There is no description for the given File', max_length=100),
        ),
    ]
