# Generated by Django 3.1.7 on 2021-03-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_drive_data_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive_data',
            name='fsize',
            field=models.CharField(default='0 bytes', max_length=15),
        ),
    ]
