# Generated by Django 3.1.7 on 2021-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_drive_data_fsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
